name: gym_hci
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  url_launcher: ^6.1.14
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^18.0.1
  fl_chart: ^0.70.2
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
